Test agent policies by deploying to ESS

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -15,7 +15,7 @@ permissions:
   pull-requests: read
 
 jobs:
-  lint:
+  lint-generate:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout
@@ -28,22 +28,97 @@ jobs:
         run: sudo apt-get install -y moreutils
 
       - name: Terraform init
-        id: tf-init
         run: terraform init -no-color
         working-directory: .github/generate
 
       - name: Terraform fmt
-        id: tf-fmt
         run: terraform fmt -no-color -check
         working-directory: .github/generate
 
       - name: Terraform Apply
-        id: tf-apply
         run: terraform apply -no-color -auto-approve
         working-directory: .github/generate
 
       - name: Check for uncommitted changes
         run: git diff && git diff --quiet
+
+  lint-deploy:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v3
+
+      - name: Setup Terraform
+        uses: hashicorp/setup-terraform@v2
+
+      - name: Terraform init
+        run: terraform init -no-color
+        working-directory: .github/deploy
+
+      - name: Terraform fmt
+        run: terraform fmt -no-color -check
+        working-directory: .github/deploy
+
+      - name: Check for uncommitted changes
+        run: git diff && git diff --quiet
+
+  deploy:
+    runs-on: ubuntu-latest
+    needs:
+      - lint-generate
+      - lint-deploy
+    environment: ess-testing
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v3
+
+      - name: Setup Terraform
+        uses: hashicorp/setup-terraform@v2
+
+      - name: Terraform init
+        run: terraform init -no-color
+        working-directory: .github/deploy
+
+      - name: Terraform Apply
+        run: terraform apply -no-color -auto-approve
+        working-directory: .github/deploy
+        env:
+          EC_API_KEY: ${{ secrets.EC_API_KEY }}
+
+      - name: Persist terraform state
+        uses: actions/upload-artifact@v3
+        with:
+          name: tfstate
+          path: .github/deploy/terraform.tfstate*
+
+  deploy-destroy:
+    runs-on: ubuntu-latest
+    if: ${{ success() || failure() }} # Always run cleanup.
+    needs:
+      - deploy
+    environment: ess-testing
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v3
+
+      - name: Setup Terraform
+        uses: hashicorp/setup-terraform@v2
+
+      - name: Terraform init
+        run: terraform init -no-color
+        working-directory: .github/deploy
+
+      - name: Restore terraform state
+        uses: actions/download-artifact@v3
+        with:
+          name: tfstate
+          path: .github/deploy/
+
+      - name: Terraform Destroy
+        run: terraform apply -destroy -no-color -auto-approve
+        working-directory: .github/deploy
+        env:
+          EC_API_KEY: ${{ secrets.EC_API_KEY }}
 
 # TODO: Add a test job that will:
 #   Spin up Elastic Cloud.
